- .vscode/settings.json
- pallets/xanchor/src/mock/parachain.rs
- pallets/xanchor/src/tests.rs
https://www.notion.so/hicommonwealth/SPEC-XAnchor-negative-tests-c93cf220d38645c0864e61880a8e56f6
> XAnchor Pallet Negtive tests

- Cargo.lock
- pallets/mixer/Cargo.toml
- pallets/mixer/src/test_utils.rs
- pallets/mixer/src/tests.rs
- primitives/Cargo.toml
- primitives/src/verifying/arkworks.rs
Reverts webb-tools/protocol-substrate#84
> Revert "Ahmed/test against wasm utils"

- .github/workflows/coverage.yaml
- README.md
- docker/Coverage.Dockerfile
> Introduce code coverage tool and add to CI

- Cargo.lock
- pallets/anchor-handler/src/mock_signature_bridge.rs
- pallets/signature-bridge/Cargo.toml
- pallets/signature-bridge/src/lib.rs
- pallets/signature-bridge/src/mock.rs
- pallets/signature-bridge/src/tests.rs
- pallets/token-wrapper-handler/src/mock_signature_bridge.rs
- primitives/src/signing/mod.rs
added nonce to set maintainer extrinsics according to #169
> add nonce to set maintainer extrinsics

- Cargo.lock
- client/Cargo.toml
- node/Cargo.toml
- pallets/anchor/Cargo.toml
- pallets/hasher/Cargo.toml
- pallets/mixer/Cargo.toml
- pallets/mt/Cargo.toml
- pallets/vanchor/Cargo.toml
- pallets/xanchor/Cargo.toml
- primitives/Cargo.toml
- standalone/node/Cargo.toml
- Update to 1.0.0 and update fixtures
> Filip/update to 1.0.0

- .gitmodules
- Update the "protocol-substrate-fixtures" submodule path
Closes
> Update the "protocol-substrate-fixtures" submodule path

- Cargo.lock
- pallets/anchor-handler/src/tests_bridge.rs
- pallets/anchor-handler/src/tests_signature_bridge.rs
- pallets/bridge/src/tests.rs
- pallets/signature-bridge/src/tests.rs
- pallets/token-wrapper-handler/src/tests_bridge.rs
- pallets/token-wrapper-handler/src/tests_signature_bridge.rs
- pallets/xanchor/src/lib.rs
- pallets/xanchor/src/tests.rs
- primitives/Cargo.toml
- primitives/src/lib.rs
- primitives/src/utils.rs
Update resource ID in XAnchor with target chain ID and target tree ID according to #183
> implement new derive resource id from webb proposal

- standalone/node/src/chain_spec.rs
- standalone/runtime/src/lib.rs
- Update the chainspec to create another asset with its mixers
Closes
> Update the chainspec to create another asset with its mixers

- .gitmodules
> Add shallow submodule configuration to save disk space

- Cargo.lock
- Cargo.toml
- pallets/vanchor-handler/Cargo.toml
- pallets/vanchor-handler/src/lib.rs
- pallets/vanchor-handler/src/mock_bridge.rs
- pallets/vanchor-handler/src/mock_signature_bridge.rs
- pallets/vanchor-handler/src/tests_bridge.rs
- pallets/vanchor-handler/src/tests_signature_bridge.rs
- pallets/vanchor-handler/src/types.rs
> Add vanchor handler separately

- pallets/anchor-handler/Cargo.toml
- pallets/anchor-handler/src/tests_signature_bridge.rs
- pallets/token-wrapper-handler/Cargo.toml
- pallets/token-wrapper-handler/src/tests_signature_bridge.rs
- pallets/xanchor/Cargo.toml
- pallets/xanchor/src/lib.rs
- pallets/xanchor/src/tests.rs
- primitives/Cargo.toml
Please check if your PR fulfills the following requirements:
Update Test cases for Pallets to use webb-proposals
What kind of change does this PR introduce?
Issue Number: #206 
Updated Xanchor Pallet to support new webb-proposal changes.
> Test webb-proposals for substrate

- pallets/anchor-handler/Cargo.toml
- pallets/anchor-handler/src/tests_signature_bridge.rs
- pallets/token-wrapper-handler/Cargo.toml
- pallets/token-wrapper-handler/src/tests_signature_bridge.rs
- pallets/xanchor/Cargo.toml
- pallets/xanchor/src/lib.rs
- pallets/xanchor/src/tests.rs
- primitives/Cargo.toml
- runtime/Cargo.toml
- runtime/src/lib.rs
- standalone/runtime/Cargo.toml
- standalone/runtime/src/lib.rs
Please check if your PR fulfills the following requirements:
Update Test cases for Pallets to use webb-proposals
What kind of change does this PR introduce?
Issue Number: N/A
- update xanchor pallet with new webb-proposal changes
Closes #211 #213
> update webb-proposals tests and add pallet-signature-bridge to runtime #209

- .gitmodules
- pallets/anchor-handler/Cargo.toml
- pallets/anchor-handler/src/lib.rs
- pallets/anchor-handler/src/mock_signature_bridge.rs
- pallets/anchor-handler/src/tests_signature_bridge.rs
- pallets/signature-bridge/src/lib.rs
- pallets/signature-bridge/src/mock.rs
- pallets/signature-bridge/src/tests.rs
- pallets/token-wrapper-handler/Cargo.toml
- pallets/token-wrapper-handler/src/mock_signature_bridge.rs
- pallets/token-wrapper-handler/src/tests_signature_bridge.rs
- pallets/vanchor-handler/Cargo.toml
- pallets/vanchor-handler/src/lib.rs
- pallets/vanchor-handler/src/mock_signature_bridge.rs
- pallets/vanchor-handler/src/tests_signature_bridge.rs
- pallets/xanchor/Cargo.toml
- primitives/Cargo.toml
- standalone/runtime/Cargo.toml
- standalone/runtime/src/lib.rs
Please check if your PR fulfills the following requirements:
Closes #221 
What kind of change does this PR introduce?
Issue Number: N/A
> set resource with signature #221

- .github/workflows/publish-docs.yml
- rust-toolchain.toml
- standalone/runtime/src/lib.rs
- Fixes doc issue by updating `rust-toolchain.toml` 
- Removes unused deps
Closes #225
> chore: remove unused deps, and fix docs issue

- README.md
- updates readme to remove stable mention
Closes
> chore: updates readme to remove stable mention

- Cargo.lock
- client/Cargo.toml
- pallets/anchor-handler/Cargo.toml
- pallets/anchor/Cargo.toml
- pallets/asset-registry/Cargo.toml
- pallets/bridge/Cargo.toml
- pallets/hasher/Cargo.toml
- pallets/linkable-tree/Cargo.toml
- pallets/linkable-tree/rpc/Cargo.toml
- pallets/linkable-tree/rpc/runtime-api/Cargo.toml
- pallets/mixer/Cargo.toml
- pallets/mt/Cargo.toml
- pallets/mt/rpc/Cargo.toml
- pallets/mt/rpc/runtime-api/Cargo.toml
- pallets/signature-bridge/Cargo.toml
- pallets/token-wrapper-handler/Cargo.toml
- pallets/token-wrapper/Cargo.toml
- pallets/vanchor-handler/Cargo.toml
- pallets/vanchor/Cargo.toml
- pallets/verifier/Cargo.toml
- pallets/xanchor/Cargo.toml
- primitives/Cargo.toml
- standalone/node/Cargo.toml
- standalone/runtime/Cargo.toml
- Bump substrate dependencies to v0.9.24
> bump substrate to 0.9.24

- README.md
- docker/Standalone.Dockerfile
- Install protobuf-compiler
```bash
apt install -y protobuf-compiler
```
- Update Readme
Closes #238
> update docker image publish job

- docker/Standalone.Dockerfile
> install protobuf-compiler

- standalone/node/src/chain_spec.rs
> Fix max edges in vanchor genesis deployments

- Cargo.lock
- Cargo.toml
- client/Cargo.toml
- client/tests/integration_tests.rs
- client/tests/utils.rs
- pallets/asset-registry/Cargo.toml
- pallets/linkable-tree/Cargo.toml
- pallets/mixer/Cargo.toml
- pallets/mixer/src/test_utils.rs
- pallets/signature-bridge/src/lib.rs
- pallets/token-wrapper-handler/Cargo.toml
- pallets/token-wrapper/Cargo.toml
- pallets/vanchor-handler/Cargo.toml
- pallets/vanchor-handler/src/mock_signature_bridge.rs
- pallets/vanchor-handler/src/tests_signature_bridge.rs
- pallets/vanchor/Cargo.toml
- pallets/vanchor/src/lib.rs
- pallets/vanchor/src/mock.rs
- pallets/vanchor/src/tests.rs
- pallets/xanchor/Cargo.toml
- pallets/xanchor/src/mock/parachain.rs
- primitives/src/types/vanchor.rs
- standalone/node/src/chain_spec.rs
- standalone/runtime/Cargo.toml
- standalone/runtime/src/lib.rs
- Update to new wasm-utils
- Update vanchor pallet to support 2 verifiers (currently fixed to a bridge of length 2)
- Update external data to support gas refund and withdrawal token
Closes
> Add refund/token to external data and handle accordingly

- .dvc/.gitignore
- .dvcignore
- .github/workflows/ci.yml
- .github/workflows/coverage.yaml
- .github/workflows/publish-docs.yml
- .gitignore
- .gitmodules
- client/tests/integration_tests.rs
- pallets/mixer/src/tests.rs
- pallets/vanchor/src/tests.rs
- pallets/xanchor/src/tests.rs
- standalone/node/src/chain_spec.rs
- substrate-fixtures.dvc
> Remove git submodules in favor of DVC

- docker/Standalone.Dockerfile
> Update dockerfile with dvc dependency

- Cargo.lock
- client/Cargo.toml
- pallets/asset-registry/Cargo.toml
- pallets/hasher/Cargo.toml
- pallets/linkable-tree/Cargo.toml
- pallets/linkable-tree/rpc/Cargo.toml
- pallets/linkable-tree/rpc/runtime-api/Cargo.toml
- pallets/mixer/Cargo.toml
- pallets/mt/Cargo.toml
- pallets/mt/rpc/Cargo.toml
- pallets/mt/rpc/runtime-api/Cargo.toml
- pallets/relayer-registry/Cargo.toml
- pallets/signature-bridge/Cargo.toml
- pallets/token-wrapper-handler/Cargo.toml
- pallets/token-wrapper/Cargo.toml
- pallets/vanchor-handler/Cargo.toml
- pallets/vanchor/Cargo.toml
- pallets/verifier/Cargo.toml
- pallets/xanchor/Cargo.toml
- primitives/Cargo.toml
- standalone/node/Cargo.toml
- standalone/node/src/chain_spec.rs
- standalone/node/src/service.rs
- standalone/runtime/Cargo.toml
- standalone/runtime/src/lib.rs
- bump deps to polkadot-v0.9.28
> bump deps to 0.9.28

- .github/workflows/coverage.yaml
- README.md
- docker/Coverage.Dockerfile
- Remove references to submodules
Closes
> Remove references to submodules

- pallets/asset-registry/Cargo.toml
- pallets/vanchor/Cargo.toml
- Minor fix to avoid errors in downstream imports
> [fix] add missing std scope for pallet

- pallets/mt/src/lib.rs
- pallets/vanchor/src/lib.rs
> Add encrypted data to vanchor event

- Cargo.lock
- pallets/asset-registry/Cargo.toml
- pallets/linkable-tree/Cargo.toml
- pallets/mixer/Cargo.toml
- pallets/token-wrapper-handler/Cargo.toml
- pallets/token-wrapper/Cargo.toml
- pallets/vanchor-handler/Cargo.toml
- pallets/vanchor/Cargo.toml
- pallets/xanchor/Cargo.toml
- standalone/runtime/Cargo.toml
- This change allows to have same version across all repos and avoid import errors in tangle repo
> [fix] use polkadot branch for orml imports

- .github/workflows/coverage.yaml
- .github/workflows/publish-docs.yml
- Updates docs jobs to include protobuf-compiler 
- Updates code coverage to include latest version and codecov token - the token shouldnt be required for public repos but seems to causing issue for others based on reported issues
Closes
> chore: updates to CI

- pallets/hasher/src/benchmarking.rs
- pallets/key-storage/src/benchmarking.rs
- pallets/mixer/src/benchmarking.rs
- pallets/mt/src/benchmarking.rs
- pallets/relayer-registry/src/benchmarking.rs
- pallets/signature-bridge/src/benchmarking.rs
- pallets/token-wrapper-handler/src/lib.rs
- pallets/token-wrapper/src/benchmarking.rs
- pallets/token-wrapper/src/lib.rs
- pallets/token-wrapper/src/tests.rs
- pallets/token-wrapper/src/traits.rs
- pallets/vanchor-handler/src/lib.rs
- pallets/vanchor-verifier/src/benchmarking.rs
- pallets/vanchor/Cargo.toml
- pallets/vanchor/src/benchmarking.rs
- pallets/verifier/src/benchmarking.rs
> substrate proposals

- .github/workflows/image-publish.yml
> Remove docker slim

- pallets/token-wrapper-handler/Cargo.toml
- pallets/vanchor-handler/Cargo.toml
- pallets/xanchor/Cargo.toml
- primitives/Cargo.toml
Updates to webb proposals 0.5.5
> update to webb proposals 0.5.5

- .dockerignore
- .github/workflows/check.yml
- Cargo.lock
- docker/Standalone.Dockerfile
- primitives/Cargo.toml
- rust-toolchain.toml
- Updated `Standalone.Dockerfile` to make use of fixtures script and reduces base image size
- Updates `check.yml` file to run build, format, and test in parallel  
- Fixes build issue
Closes
> chore: updates and fixes Dockerfile and build

- .github/workflows/check.yml
- .github/workflows/publish-docs.yml
- use build instead of check
- fixes doc build
Closes
> chore: use build instead of check

- docker/Standalone.Dockerfile
- Updates base to remove use of alpine
Closes
> chore: fix base image

- pallets/signature-bridge/src/lib.rs
- primitives/src/traits/mod.rs
- primitives/src/traits/signature_bridge.rs
- Adds SetMaintainer trait for directly setting maintainer from external systems (DKG for example).
> Add SetMaintainer trait and implement for signature bridge

- pallets/signature-bridge/src/lib.rs
- pallets/signature-bridge/src/tests.rs
- pallets/token-wrapper-handler/src/tests_signature_bridge.rs
- pallets/vanchor-handler/src/tests_signature_bridge.rs
-  update `force_set_maintainer` to set maintainer nonce as well
Closes
> Update force set maintainer

- .github/workflows/publish-types.yml
- .github/workflows/update-types.yml
> Update CI's Nodejs to v18

- .envrc
- .gitignore
- README.md
- flake.lock
- flake.nix
- rust-toolchain.toml
- Added Nix with Flakes devenv
- Update the README on how to utilize it.
Closes
> Add Nix flakes devenv
